/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_20130803_proyecto_04;

import Utilerias.JTable.ColorCeldas;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cgl05
 */
public class PA_20130803_Frame_04 extends javax.swing.JFrame {

    /**
     * Creates new form PA_20130803_Frame_01
     */
    private DefaultTableModel modelo;
    private ColorCeldas color;
    int r, c, colorInicial;
    Inventario consumo, promedio, inicial, fin;
    JFileChooser jfch = new JFileChooser();
    
    
    public void borrarColorTabla()
    {
        for (r = 0; r < modelo.getRowCount(); r++)
            for (c = 0; c < modelo.getColumnCount(); c++)
                color.addCelda(r,c, Color.white);
        color.repaint();
    }
    
    public void sobrepasaPromedio()
    {
        for (r = 0; r < modelo.getRowCount(); r++) 
        {
            consumo = new Inventario(Integer.parseInt(modelo.getValueAt(r, 7) + ""),Integer.parseInt(modelo.getValueAt(r, 8) + ""),Integer.parseInt(modelo.getValueAt(r, 9) + ""));
            if(consumo.mayorQue(promedio))
            {
                for(c = 0; c < modelo.getColumnCount(); c++)
                   color.addCelda(r, c, Color.yellow);
                color.repaint();
            }   
        }
    }
    
    public void borrarDatos()
    {
        jLabTotal.setText("");
        jLabPromedio.setText(""); 
        jSpinObras.setValue(0);
    }
    
    public PA_20130803_Frame_04() {
        initComponents();
        modelo = (DefaultTableModel) jTableObras.getModel();
        colorInicial = getContentPane().getBackground().getRGB();
        
        jTableObras.setShowGrid(true);
        
        color = new ColorCeldas(jTableObras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableObras = new javax.swing.JTable();
        jButCalcular = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jSpinObras = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButEjemplo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabPromedio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemGrabar = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCambiarColor = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Obra", "Toneldas", "Bultos", "Kilos", "Toneladas", "Bultos", "Kilos", "Toneladas", "Bultos", "Kilos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableObras);
        if (jTableObras.getColumnModel().getColumnCount() > 0) {
            jTableObras.getColumnModel().getColumn(0).setResizable(false);
            jTableObras.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jSpinObras.setModel(new javax.swing.SpinnerNumberModel());
        jSpinObras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinObrasStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Numero de obras");

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventario Inicial");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(153, 255, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventario Final");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consumo");
        jLabel5.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Consumo Total:");

        jLabTotal.setBackground(new java.awt.Color(255, 51, 51));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabTotal.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Consumo Promedio:");

        jLabPromedio.setBackground(new java.awt.Color(51, 255, 204));
        jLabPromedio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabPromedio.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Nombre: Carson Alejandro Gomez Lugo");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Numero de control: 20130803");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Numero de Proyecto: 04");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Descripcion: Esta Aplicacion mejora y actualiza la creada en el");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("proyecto numero 2, con guardado lectura, y optimizacion de");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("codigo");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_20130803_proyecto_04/Asignacion_P2.PNG"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_20130803_proyecto_04/Ejemplo POO P2_21_1 EneJun. Cemento constructora.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_20130803_proyecto_04/AsignacionEJ21_P4.png"))); // NOI18N

        jLabel16.setBackground(new java.awt.Color(0, 51, 153));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Asignacion P2");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Asignacion P4");
        jLabel17.setOpaque(true);

        jMenu1.setText("Archivo");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNuevo);

        jMenuItemGrabar.setText("Grabar");
        jMenuItemGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrabarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGrabar);

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbrir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        jMenuItemCambiarColor.setText("Cambiar Color de Frame");
        jMenuItemCambiarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarColorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCambiarColor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinObras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButCalcular)
                        .addGap(30, 30, 30)
                        .addComponent(jButAleatorios)
                        .addGap(28, 28, 28)
                        .addComponent(jButEjemplo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel17)))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButAleatorios)
                            .addComponent(jButCalcular)
                            .addComponent(jSpinObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButEjemplo))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinObrasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinObrasStateChanged
        // TODO add your handling code here:
        modelo.setRowCount((int)jSpinObras.getValue());
    }//GEN-LAST:event_jSpinObrasStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        borrarColorTabla();
        borrarDatos();
        
        jSpinObras.setValue(azar.nextInt(15)+1);
        
        String [] obras = {"Casa", "Plaza", "Cancha", "Parque",
                            "Edificio", "Centro Comercial", "Estadio", "Hotel",
                            "Comercio", "Farmacia", "Local", "Oficina",
                            "Departamento", "Hospital", "Escuela", "Aeropueto",
                            "Puente", "Puerto", "Restaurante", "Muebleria", "Ferreteria"};
        
        for (r = 0; r < modelo.getRowCount(); r++)
        {            
            modelo.setValueAt(obras[azar.nextInt(obras.length)], r, 0);
            
            modelo.setValueAt(azar.nextInt(120)+ 60, r, 1);
            modelo.setValueAt(azar.nextInt(20), r, 2);
            modelo.setValueAt(azar.nextInt(50), r, 3);
            
            modelo.setValueAt(azar.nextInt(60), r, 4);
            modelo.setValueAt(azar.nextInt(20), r, 5);
            modelo.setValueAt(azar.nextInt(50), r, 6);
        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        borrarColorTabla();
        borrarDatos();
        
        jSpinObras.setValue(4);
        
        modelo.setValueAt("Edificio", 0, 0);
        modelo.setValueAt(15, 0, 1);
        modelo.setValueAt(18, 0, 2);
        modelo.setValueAt(6, 0, 3);
        modelo.setValueAt(2, 0, 4);
        modelo.setValueAt(7, 0, 5);
        modelo.setValueAt(10, 0, 6);

        modelo.setValueAt("Plaza", 1, 0);
        modelo.setValueAt(248, 1, 1);
        modelo.setValueAt(9, 1, 2);
        modelo.setValueAt(2, 1, 3);
        modelo.setValueAt(170, 1, 4);
        modelo.setValueAt(19, 1, 5);
        modelo.setValueAt(49, 1, 6);

        modelo.setValueAt("Escuela", 2, 0);
        modelo.setValueAt(38, 2, 1);
        modelo.setValueAt(1, 2, 2);
        modelo.setValueAt(11, 2, 3);
        modelo.setValueAt(3, 2, 4);
        modelo.setValueAt(2, 2, 5);
        modelo.setValueAt(2, 2, 6);

        modelo.setValueAt("Oficinas", 3, 0);
        modelo.setValueAt(8, 3, 1);
        modelo.setValueAt(14, 3, 2);
        modelo.setValueAt(3, 3, 3);
        modelo.setValueAt(1, 3, 4);
        modelo.setValueAt(16, 3, 5);
        modelo.setValueAt(4, 3, 6);
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        inicial = new Inventario();
        fin = new Inventario();
        Inventario consumoTotal = new Inventario();
        
        borrarColorTabla();

        for (r = 0; r < modelo.getRowCount(); r++)
        {
            inicial.setToneladas(Integer.parseInt(modelo.getValueAt (r, 1) + ""));
            inicial.setBultos(Integer.parseInt(modelo.getValueAt (r, 2) + ""));
            inicial.setKilos(Integer.parseInt(modelo.getValueAt (r, 3) + ""));
            
            fin.setToneladas(Integer.parseInt(modelo.getValueAt (r, 4) + ""));
            fin.setBultos(Integer.parseInt(modelo.getValueAt (r, 5) + ""));
            fin.setKilos(Integer.parseInt(modelo.getValueAt (r, 6) + ""));
            
            consumo = inicial.resta(fin);
            consumoTotal = consumoTotal.suma(consumo);
            
            modelo.setValueAt(consumo.getToneladas(), r, 7);
            modelo.setValueAt(consumo.getBultos(), r, 8);
            modelo.setValueAt(consumo.getKilos(), r, 9);            
        }
        
        promedio = consumoTotal.division(modelo.getRowCount());
        
        sobrepasaPromedio();
        
        jLabTotal.setText(consumoTotal + "");
        jLabPromedio.setText(promedio + "");
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // TODO add your handling code here:
        borrarColorTabla();
        borrarDatos();
        getContentPane().setBackground(new Color(colorInicial));
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemCambiarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarColorActionPerformed
        // TODO add your handling code here:
        JColorChooser jcch = new JColorChooser();
        JPanel panel = new JPanel();
        getContentPane().setBackground(jcch.showDialog(panel,"Selector de color",Color.white));
    }//GEN-LAST:event_jMenuItemCambiarColorActionPerformed

    private void jMenuItemGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrabarActionPerformed
        // TODO add your handling code here:
        Obra [] lista = new Obra[modelo.getRowCount()];
        
        for (r = 0; r < modelo.getRowCount(); r++) 
            {
                inicial = new Inventario();
                fin = new Inventario();

                inicial.setToneladas(Integer.parseInt(modelo.getValueAt(r, 1) + ""));
                inicial.setBultos(Integer.parseInt(modelo.getValueAt(r, 2) + ""));
                inicial.setKilos(Integer.parseInt(modelo.getValueAt(r, 3) + ""));

                fin.setToneladas(Integer.parseInt(modelo.getValueAt(r, 4) + ""));
                fin.setBultos(Integer.parseInt(modelo.getValueAt(r, 5) + ""));
                fin.setKilos(Integer.parseInt(modelo.getValueAt(r, 6) + ""));

                Obra obr = new Obra(modelo.getValueAt(r, 0) + "", inicial, fin);

                lista[r] = obr;
            }
            
        Arrays.sort(lista);
        
        if(jfch.showSaveDialog(jLabel1) != 0)
            return;
        
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        
        try {
            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);
            
            dos.writeInt(modelo.getRowCount());
            dos.writeInt(getContentPane().getBackground().getRGB());
            
            for (int i = 0; i < lista.length; i++)
            {
                dos.writeUTF(lista[i].getNombre());
                dos.writeInt(lista[i].getInicial().getToneladas());
                dos.writeInt(lista[i].getInicial().getBultos());
                dos.writeInt(lista[i].getInicial().getKilos());
                dos.writeInt(lista[i].getFin().getToneladas());
                dos.writeInt(lista[i].getFin().getBultos());
                dos.writeInt(lista[i].getFin().getKilos());  
            }
            
        JOptionPane.showMessageDialog(rootPane, "Archivo " + jfch.getSelectedFile() + " ha sido grabado exitosamente");
            
        } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(rootPane, "Error al grabar " + jfch.getSelectedFile());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al grabar " + jfch.getSelectedFile());
        }
        finally
        {
            if(dos != null)
                try {
                    dos.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(fos != null)
                try {
                    fos.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
                        
        }
    }//GEN-LAST:event_jMenuItemGrabarActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:
        if(jfch.showOpenDialog(jLabel1) != 0)
            return;
        
        FileInputStream fis = null;
        DataInputStream dis = null;
        
        try {
            fis = new FileInputStream(jfch.getSelectedFile());
            dis = new DataInputStream(fis);
            
            jSpinObras.setValue(dis.readInt());
            getContentPane().setBackground(new Color(dis.readInt()));
            
            for (int r = 0; r < modelo.getRowCount();r++) 
            {
                modelo.setValueAt(dis.readUTF(), r, 0);
                modelo.setValueAt(dis.readInt(), r, 1);
                modelo.setValueAt(dis.readInt(), r, 2);
                modelo.setValueAt(dis.readInt(), r, 3);
                modelo.setValueAt(dis.readInt(), r, 4);
                modelo.setValueAt(dis.readInt(), r, 5);
                modelo.setValueAt(dis.readInt(), r, 6);
            }
            jButCalcular.doClick();
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al abrir " + jfch.getSelectedFile());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al abrir " + jfch.getSelectedFile());
        }
        finally
        {
            if(dis != null)
                try {
                    dis.close();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(rootPane, "Error al abrir " + jfch.getSelectedFile());
            }
            if(fis != null)
                try {
                    fis.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error al abrir " + jfch.getSelectedFile());
            }
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_20130803_Frame_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabPromedio;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemCambiarColor;
    private javax.swing.JMenuItem jMenuItemGrabar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinObras;
    private javax.swing.JTable jTableObras;
    // End of variables declaration//GEN-END:variables
}
